# Generated by Django 5.0.6 on 2024-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
