# Generated by Django 5.0.6 on 2024-10-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
