# Generated by Django 5.0.6 on 2024-09-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_forumthread_forumpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumthread',
            old_name='creator',
            new_name='author',
        ),
        migrations.AddField(
            model_name='forumthread',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
