# Generated by Django 5.0.6 on 2024-09-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_creator_forumthread_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.customuser'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='comments_media/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='group.customuser')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='group.forumthread')),
            ],
        ),
    ]
