# Generated by Django 5.0.6 on 2024-09-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('day_month_year', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
