# Generated by Django 5.0.6 on 2024-09-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('group', '0009_subject_reportcard_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to='authentication.customuser'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member_of_groups', to='authentication.customuser'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
