# Generated by Django 5.0.6 on 2024-09-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('group', '0010_alter_group_admin_alter_group_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumthread',
            name='author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumthread'),
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='ForumThread',
        ),
    ]
