# Generated by Django 5.0.6 on 2024-09-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_remove_forumthread_author_alter_comment_thread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='student',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='ReportCard',
        ),
    ]
