# Generated by Django 5.0.6 on 2024-09-28 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('group', '0012_remove_reportcard_student_delete_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comment.comment'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
