# Generated by Django 5.0.6 on 2024-09-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0013_alter_like_comment_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
