# Generated by Django 5.0.6 on 2024-09-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
