# Generated by Django 5.0.6 on 2024-09-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('details', models.CharField(default='', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_media/')),
                ('status', models.CharField(default='member', max_length=30)),
            ],
        ),
    ]
